# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: eggplant-runner@2
  inputs:
    daiVersion: '26.1.0+4'
    serverURL: 'https://dai.eggplantlab.com/'
    testConfig: 'ById'
    testConfigID: 'ba019c3d-1dac-43fe-9c7b-82e73c516be0'
    clientID: 'client:dai:api:integration:dffb0dc9-5935-445a-a9c5-2ea646e12bf2'
    clientSecret: '2twKTNRHKjuTXYKMuWHcXhhF6eKs8AqF'
